# Generated by Django 3.2.6 on 2021-10-29 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211028_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 17, 59, 28, 222735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 17, 59, 28, 223636, tzinfo=utc)),
        ),
    ]
