# Generated by Django 3.2.6 on 2021-10-29 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211029_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 18, 0, 42, 656561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 18, 0, 42, 657664, tzinfo=utc)),
        ),
    ]
