# Generated by Django 3.2.6 on 2021-10-30 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211029_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 16, 37, 50, 809706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 16, 37, 50, 810631, tzinfo=utc)),
        ),
    ]
