# Generated by Django 3.2.6 on 2021-10-30 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211030_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 16, 43, 56, 445477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2021, 10, 30, 16, 43, 56, 446492, tzinfo=utc)),
        ),
    ]
